version: "3.9"
services:
  flowers-store-api-db:
    image: postgres:14.0-alpine
    restart: unless-stopped
    volumes:
      - /flowers-store-api/${FLOWERS_STORE_API_ENVIRONMENT}/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${FLOWERS_STORE_API_POSTGRES_DB}
      - POSTGRES_USER=${FLOWERS_STORE_API_POSTGRES_USER}
      - POSTGRES_PASSWORD=${FLOWERS_STORE_API_POSTGRES_PASSWORD}
  flowers-store-api:
    image: longmont.iguzman.com.mx:5000/flowers-store-api:latest
    restart: unless-stopped
    environment:
      - SECRET_KEY=${FLOWERS_STORE_API_SECRET_KEY}
      - ENVT=${FLOWERS_STORE_API_ENVIRONMENT}
      - DB_NAME=${FLOWERS_STORE_API_POSTGRES_DB}
      - DB_USER=${FLOWERS_STORE_API_POSTGRES_USER}
      - DB_PASSWORD=${FLOWERS_STORE_API_POSTGRES_PASSWORD}
      - EMAIL_HOST_USER=${FLOWERS_STORE_API_EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${FLOWERS_STORE_API_EMAIL_HOST_PASSWORD}
    volumes:
      - /flowers-store-api/${FLOWERS_STORE_API_ENVIRONMENT}/static:/static
      - /flowers-store-api/${FLOWERS_STORE_API_ENVIRONMENT}/media:/media
    ports:
      - "${FLOWERS_STORE_API_PUBLIC_PORT}:8000"
    depends_on:
      - flowers-store-api-db
